<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="NewFile" targetNamespace="http://www.example.org/NewFile/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/NewFile/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="NewFile_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="NewFileSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.example.org/NewFile/">
<xsd:include schemaLocation="NewFile_InlineSchema1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="AddRequest">
    <wsdl:part element="tns:Add" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="AddResponse">
    <wsdl:part element="tns:AddResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Add">
    <wsdl:operation name="Add">
      <wsdl:input message="tns:AddRequest"/>
      <wsdl:output message="tns:AddResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="NewFileSOAP" type="tns:Add">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Add">
      <soap:operation soapAction="http://www.example.org/NewFile/Add"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NewFile">
    <wsdl:port binding="tns:NewFileSOAP" name="NewFileSOAP">
      <soap:address location="http://localhost:7800/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>