<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="MultiplicationCode" targetNamespace="http://www.example.org/MultiplicationCode/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/MultiplicationCode/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="MultiplicationCode_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="MultiplicationCodeSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.example.org/MultiplicationCode/">
<xsd:include schemaLocation="MultiplicationCode_InlineSchema1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="MultiplicationRequest">
    <wsdl:part element="tns:Multiplication" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="MultiplicationResponse">
    <wsdl:part element="tns:MultiplicationResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="MultiplicationCode">
    <wsdl:operation name="Multiplication">
      <wsdl:input message="tns:MultiplicationRequest"/>
      <wsdl:output message="tns:MultiplicationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MultiplicationCodeSOAP" type="tns:MultiplicationCode">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Multiplication">
      <soap:operation soapAction="http://www.example.org/MultiplicationCode/Multiplication"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MultiplicationCode">
    <wsdl:port binding="tns:MultiplicationCodeSOAP" name="MultiplicationCodeSOAP">
      <soap:address location="http://localhost:7800/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>